easy_admin:
    # disabled_actions: ['new']
    design:
        menu:
            - { label: 'Resume Page', route: 'homepage' }
            - { label: 'Profile Page', route: 'musician_profile' }
            # - { label: 'Profile', route: 'musician_show', params: { username: "{{musician.username}}"} }
            - label: 'Education'
              children: ['Education', 'Specialty', 'Document']                        
            - label: 'Jobs'
              children: ['Job', 'JobRole']                        
            - { entity: 'Skill', label: 'Skills' }            
            - { entity: 'Project', label: 'Projects' }            
            - { entity: 'Role', label: "Jobs you can do" }            
            - { entity: 'Gallery', label: "Photos and Videos" }            
            - { entity: 'PdfTheme', label: "Pdf Resume" }            
            - { entity: 'WebTheme', label: "Web Theme" }            
            - { entity: 'Musician', label: "Musicians" }            
            # - { label: 'Some Task', route: 'user_some_task' }
            # - { label: 'Other Task', route: 'other_task', params: { max: 7 } }

    site_name: 'Your Admin Page'

    formats:
        date:     'M Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    entities:
        Education:
            disabled_actions: ['new']
            class: App\Entity\Education
            label: 'Education'
            list:
                title: "Education background"    
                fields: ['institution', {property: 'fromyear', label: 'From'}, {property: 'toyear', label: 'To'}, {property: 'coursename', label: 'Course'}, 'degree', 'location']        
                sort: ['toyear', 'DESC']
            search:
                sort: ['toyear', 'DESC']    
            form:
                fields: ['institution', {property: 'fromyear', label: 'From'}, {property: 'toyear', label: 'To'}, {property: 'coursename', label: 'Course'}, 'degree', 'location']        
        Job:
            disabled_actions: ['new']
            class: App\Entity\Job
            label: 'Jobs'
            list:
                title: "Job Experience"            
                fields: ['jobtitle', {property: 'startingfrom', label: 'From'}, {property: 'endedin', label: 'To'}, {property: 'currentornot', label: 'Current Job?'}, 'location', 'institution']
            search:
                sort: ['endedin', 'DESC']  
            form:
                fields: ['jobtitle', {property: 'startingfrom', label: 'From'}, {property: 'endedin', label: 'To'}, {property: 'currentornot', label: 'Current Job?'}, 'location', 'institution']                              
        Role:
            disabled_actions: ['new']
            class: App\Entity\JobToBeOffered
            label: 'Roles'
            list:
                title: "Roles you can play"   
                fields: [{property: 'medium', label: 'Medium'}, , {property: 'jobtitle', label: 'Job Title'}] 
            form:
                fields: [{property: 'medium', label: 'Medium'}, , {property: 'jobtitle', label: 'Job Title'}] 
        JobRole:
            disabled_actions: ['new']
            class:  App\Entity\Role
            label: 'Job Roles'
            list:
                title: "Roles for your jobs"            
                fields: ['role', 'job']
            form:
                fields: ['role', 'job']
        Project:
            disabled_actions: ['new']
            class: App\Entity\Project
            label: 'Projects'
            list:
                title: "Projects you've done"            
                fields: [{property: 'projecttitle', label: 'Project Title'}]
            form:
                fields: [{property: 'projecttitle', label: 'Project Title'}]
        Skill:
            disabled_actions: ['new']
            class: App\Entity\Skill
            label: 'Skills'
            list:
                title: "Your skills"            
                fields: [{property: 'skillname', label: 'Skill'}, {property: 'levelofskill', label: 'Leveo of Skill'}, {property: 'experienceofskill', label: 'Experience in Years'}]                        
            form:
                fields: [{property: 'skillname', label: 'Skill'}, {property: 'levelofskill', label: 'Leveo of Skill'}, {property: 'experienceofskill', label: 'Experience in Years'}]                        
        Specialty:
            disabled_actions: ['new']
            class: App\Entity\Specialty
            label: 'Skills learned'
            list:
                title: "Skills earned"            
                fields: [{property: 'instrumentorskill', label: 'Skills earned'}, {property: 'education.coursename', label: 'Course'}, {property: 'education.degree', label: 'Level'}]                        
            form:
                fields: [{property: 'instrumentorskill', label: 'Skills earned'}, {property: 'education.coursename', label: 'Course'}, {property: 'education.degree', label: 'Level'}]                        
        Document:
            disabled_actions: ['new']
            class: App\Entity\Document
            label: 'Documents'
            list:
                title: "Your Documents"            
                fields: [{property: 'doc', label: 'Document'}, {property: 'education.coursename', label: 'Course'}, {property: 'education.degree', label: 'Level'}]                        
            form:
                fields: [{property: 'doc', label: 'Document'}, {property: 'education.coursename', label: 'Course'}, {property: 'education.degree', label: 'Level'}]                        
        Gallery:
            disabled_actions: ['new']
            class: App\Entity\Gallery
            label: 'Photos & Videos'
            list:
                title: "Gallery"            
                fields: [{property: 'photo', label: 'Media'}, {property: 'description', label: 'Description'}]                        
            form:
                fields: [{property: 'photo', label: 'Media'}, {property: 'description', label: 'Description'}]                        
        Musician:
            disabled_actions: ['new']
            class: App\Entity\Musician
            label: 'Musicians'
            list:
                title: "Musicians"            
                fields: [{property: 'fullname', label: 'Full Name'}, {property: 'username', label: 'Username'}, {property: 'realemail', label: 'Email'}, {property: 'confirmed', label: 'Email Confirmation'}, {property: 'subscribed', label: 'Subscription'}, {property: 'realphone', label: 'Phone'}, {property: 'account', label: 'Account'}]                        
            form:
                fields: [{property: 'fullname', label: 'Full Name'}, {property: 'username', label: 'Username'}, {property: 'realemail', label: 'Email'}, {property: 'confirmed', label: 'Email Confirmation'}, {property: 'subscribed', label: 'Subscription'}, {property: 'realphone', label: 'Phone'}, {property: 'account', label: 'Account'}] 
        PdfTheme:
            class: App\Entity\PdfTheme
            label: 'Pdf Resume'
            list:
                actions: ['list', 'edit', 'search', 'delete', 'show', 'new']
                title: "Resume"            
                fields: [{property: 'template', label: 'Template'}, {property: 'screenshot', label: 'Screenshot'}, {property: 'title', label: 'Title'}]                        
            form:
                fields: [{property: 'template', label: 'Template'}, {property: 'screenshot', label: 'Screenshot'}, {property: 'title', label: 'Title'}]                        
        WebTheme:
            class: App\Entity\WebTheme
            label: 'Web Theme'
            list:
                actions: ['list', 'edit', 'search', 'delete', 'show', 'new']
                title: "Web Resume"            
                fields: [{property: 'template', label: 'Template'}, {property: 'screenshot', label: 'Screenshot'}, {property: 'title', label: 'Title'}]                        
            form:
                fields: [{property: 'template', label: 'Template'}, {property: 'screenshot', label: 'Screenshot'}, {property: 'title', label: 'Title'}]                        
    user:
        # this method/property must return the string representation of the user
        # (Symfony will look for getFullName(), isFullName(), ..., and 'fullName' property)
        name_property_path: 'fullname'
        # this method/property must return the absolute URL of the user avatar image
        # (Symfony will look for getGravatar(), isGravatar(), ..., and 'gravatar' property)
        avatar_property_path: 'thumbnailurl'
        # **/vendor/**/{Tests,tests}/**