# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: my_config        
    configs:
        my_config:
            toolbar: [ ["Bold"], ["Italic"], ["Underline"], ["NumberedList"], ["BulletedList"], ["Blockquote"] , ["JustifyLeft"], ["JustifyCenter"], ["JustifyRight"], ["Link"], ["Image"] ]
            # filebrowserUploadRoute: "post_new"

    input_sync: true