# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: my_config        
    configs:
        my_config:
            toolbar: [ ["Maximize"], ["Cut"], ["Copy"], ["Paste"], ["Find"], ["Replace"], ["Styles"], ["Format"] "/", ["Bold"], ["Italic"], ["Underline"], ["Subscript"], ["Superscript"], ["NumberedList"], ["BulletedList"], ["Indent"], ["Blockquote"] "/", ["JustifyLeft"], ["JustifyCenter"], ["JustifyRight"], ["Link"], ["Unlink"], ["Image"], ["Iframe"], ["Font"], ["FontSize"] ]
            # filebrowserUploadRoute: "post_new"

    input_sync: true