knp_snappy:
    pdf:
        enabled:    true
        binary:     "%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64"
        options:
            - { name: 'viewport-size', value: ‘1024x768’ }
            - { name: 'page-size', value: 'A4' }  
            - { name: 'javascript-delay', value: '20' }      
    image:
        enabled:    true
        binary:     "%kernel.project_dir%/vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64"
        options:
            - { name: 'quality', value: '80'}