controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

oa_rating:
    resource: '@RatingBundle/Controller'
    type: annotation
